version: '3.3'
services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: database
    ports:
      - '5432:5432'
    volumes:
      - my-db:/var/lib/postgres
volumes:
  my-db: