version: '3.3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: workout
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - my-db:/var/lib/postgres
volumes:
  my-db: