version: '3.3'
services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: database
    ports:
      - '5432:5432'
    volumes:
      - my-db:/var/lib/postgres
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client
    command: npm run start
    ports:
      - '8080:8080'
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    command:  bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -e production"
    ports:
      - '3000:3000'
    # Allows us to reference the postgres container inside our rails application
    links:
      - "db:db"
volumes:
  my-db: